import { makeFeeds, mapHelper } from "../utils.ts"

export default makeFeeds(
  mapHelper([
    { key: "World" },
    { key: "Africa" },
    { key: "Americas" },
    { name: "Asia Pacific", key: "AsiaPacific" },
    { key: "Europe" },
    { key: "MiddleEast" },
    { name: "U.S.", key: "US" },
    { key: "Education" },
    { name: "The Upshot", key: "Upshot" },
    { key: "Politics" },
    { name: "N.Y./Region", key: "NYRegion" },
    { key: "Business" },
    { name: "Energy & Environment", key: "EnergyEnvironment" },
    { name: "Small Business", key: "SmallBusiness" },
    { key: "Economy" },
    { name: "DealBook", key: "Dealbook" },
    { name: "Media & Advertising", key: "MediaandAdvertising" },
    { name: "Your Money", key: "YourMoney" },
    { key: "Technology" },
    { name: "Personal Tech", key: "PersonalTech" },
    { key: "Sports" },
    { key: "Baseball" },
    { name: "College Basketball", key: "CollegeBasketball" },
    { name: "College Football", key: "CollegeFootball" },
    { key: "Golf" },
    { key: "Hockey" },
    { name: "Pro-Basketball", key: "ProBasketball" },
    { name: "Pro-Football", key: "ProFootball" },
    { key: "Soccer" },
    { key: "Tennis" },
    { key: "Science" },
    { name: "Environment", key: "Climate" },
    { name: "Space & Cosmos", key: "Space" },
    { key: "Health" },
    { name: "Well Blog", key: "Well" },
    { key: "Arts" },
    { name: "Art & Design", key: "ArtandDesign" },
    { name: "Book Review", key: "Books/Review" },
    { key: "Dance" },
    { key: "Movies" },
    { key: "Music" },
    { key: "Television" },
    { key: "Theater" },
    { name: "Fashion & Style", key: "FashionandStyle" },
    { name: "Dining & Wine", key: "DiningandWine" },
    { name: "Love", key: "Weddings" },
    { name: "T Magazine", key: "tmagazine" },
    { key: "Travel" },
    { key: "Jobs" },
    { name: "Real Estate", key: "RealEstate" },
    { name: "Autos", key: "Automobiles" },
    { name: "Lens Blog", key: "Lens" },
    { key: "Obituaries" },
    { name: "Times Wire", key: "recent" },
    { name: "Most E-Mailed", key: "MostEmailed" },
    { name: "Most Shared", key: "MostShared" },
    { name: "Most Viewed", key: "MostViewed" },
    { name: "Sunday Opinion", key: "sunday-review" },
    { name: "Top", key: "HomePage" },
  ], f => ({
    name: (f.name ?? f.key) + " - The New York Times",
    description: "https://www.nytimes.com/rss",
    url: `https://rss.nytimes.com/services/xml/rss/nyt/${f.key}.xml`,
    icon: "https://nytco-assets.nytimes.com/2021/09/NYTCO-WhiteT.jpg",
    base: "https://rss.nytimes.com",
    threadName: "The New York Times",
  })),
  mapHelper([
    { name: "Charles M. Blow", key: "charles-m-blow" },
    { name: "Jamelle Bouie", key: "jamelle-bouie" },
    { name: "David Brooks", key: "david-brooks" },
    { name: "Frank Bruni", key: "frank-bruni" },
    { name: "Gail Collins", key: "gail-collins" },
    { name: "Ross Douthat", key: "ross-douthat" },
    { name: "Maureen Dowd", key: "maureen-dowd" },
    { name: "Thomas L. Friedman", key: "thomas-l-friedman" },
    { name: "Michelle Goldberg", key: "michelle-goldberg" },
    { name: "Ezra Klein", key: "ezra-klein" },
    { name: "Nicholas D. Kristof", key: "nicholas-kristof" },
    { name: "Paul Krugman", key: "paul-krugman" },
    { name: "Farhad Manjoo", key: "farhad-manjoo" },
    { name: "Bret Stephens", key: "bret-stephens" },
  ], f => ({
    name: f.name + "'s Column - The New York Times",
    description: "https://www.nytimes.com/rss",
    url: `https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/${f.key}/rss.xml`,
    icon: "https://nytco-assets.nytimes.com/2021/09/NYTCO-WhiteT.jpg",
    base: "https://rss.nytimes.com",
    threadName: "The New York Times",
  })),
)
