on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno
          restore-keys: |
            deno-check-cache-
            deno-cache-
          key: deno-check-cache-${{ hashFiles('./deno.lock') }}
          # save-always: true

      - run: deno check src/main.ts
        if: ${{ !cancelled() }}

      - run: deno lint
        if: ${{ !cancelled() }}
