on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/deno
          restore-keys: deno-deps-
          key: deno-deps-${{ hashFiles('./deno.jsonc') }}

      - run: deno lint --unstable
