on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1

      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno
          restore-keys: deno-cache-
          key: deno-cache-${{ hashFiles('./deno.lock') }}
          save-always: true

      - run: deno lint
        if: ${{ !cancelled() }}

      - run: deno check main.ts
        if: ${{ !cancelled() }}
