on:
  push:
    branches:
      - main

  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

concurrency:
  group: main
  # 先の実行がキャンセルされるため
  #cancel-in-progress: true

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1

      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno
          restore-keys: deno-cache-
          key: deno-cache-${{ hashFiles('./deno.lock') }}
          save-always: true

      - run: deno run --unstable-kv --allow-env --allow-net --allow-read=. --allow-write=. ./main.ts
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Run"
            git push
          fi

      # - run: |
      #     gh api "repos/akku1139/RSS2Discord/actions/workflows/run.yml/runs?per_page=100"
      #     | jq -r '.workflow_runs[].id'
      #     | xargs -P4 -I{} gh api repos/akku1139/RSS2Discord/actions/runs/{} -X DELETE
      #   env:
      #     GH_TOKEN: ${{ github.token }}
