on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      args:
        type: string
        required: false
        description: 'Args'
        default: ''

  schedule:
    - cron: '*/5 * * * *'

concurrency:
  group: main

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno
          restore-keys: deno-cache-
          key: deno-cache-${{ hashFiles('./deno.lock') }}
          # save-always: true

      - run: git pull

      - run: deno run --unstable-kv --allow-env --allow-net --allow-read=. --allow-write=. ./src/main.ts ${{ inputs.args }}
        env:
          DEFAULT_WEBHOOK_URL: ${{ secrets.DEFAULT_WEBHOOK_URL }}
          FORUM_WEBHOOK_URL: ${{ secrets.FORUM_WEBHOOK_URL }}
          TRANS_WEBHOOK_URL: ${{ secrets.TRANS_WEBHOOK_URL }}

      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git pull
            git commit -m "Run"
            git push
          fi
