on:
  schedule:
    - cron: '*/5 * * * *'

concurrency:
    group: main
    cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/cache@v4
        with:
          path: |
            ./db/
            ${{ grep "DENO_DIR" | cut -d \" -f 2 }}/
          key: deno-deps-db

      - run: deno run ./main.ts
