on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

concurrency:
    group: main
    cancel-in-progress: true

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/deno
          restore-keys: deno-deps-
          key: deno-deps-${{ hashFiles('./deno.jsonc') }}

      - run: deno run --unstable-kv --allow-env="WEBHOOKS" --allow-net --allow-read=. --allow-write=. ./main.ts
        env:
          WEBHOOKS: ${{ secrets.WebHooks }}

      - run: |
         if [ -n "$(git status --porcelain)" ]; then
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
           git add -A
           git commit -m "DB"
           git push
         fi
